### ISSUE TITLE
nothing happend 

### ISSUE THREAD

**Issue by JeremyWebb12** [BeepFelix/CSGO---Discord-RichEmbed#1]
followed all steps yet nothing at all happened

**Comment by BeepIsla** [comment]
Nothing happens if you manually start it or when you use PM2 or both?

Try `node index.js`, does that show anything on Discord after you start CSGO? *(Can take up to 10 seconds for it to update)*

Is your `gamestate_integration_discord.cfg` in the correct folder? (`<Steam>\steamapps\common\Counter-Strike Global Offensive\csgo\cfg`)

Does your `uri` parameter inside the `gamestate_integration_discord.cfg` have the same port as the one defined in `config.json`?

Does your `token` parameter inside the `gamestate_integration_discord.cfg` have the same auth string as the one defined in `config.json`?

**Comment by JeremyWebb12** [comment]
**Nothing happens if you manually start it or when you use PM2 or both?**
Both
**Try node index.js, does that show anything on Discord after you start CSGO? (Can take up to 10 seconds for it to update)**
only thing that happens is displaying how much time I have played

**Is your gamestate_integration_discord.cfg in the correct folder? (<Steam>\steamapps\common\Counter-Strike Global Offensive\csgo\cfg)
Does your uri parameter inside the gamestate_integration_discord.cfg have the same port as the one defined in config.json?
Does your token parameter inside the gamestate_integration_discord.cfg have the same auth string as the one defined in config.json?**
yes they are all correct 
also probably should've mentioned this but in powershell (I cant open in cmd) it says: **Steam API Key is invalid or Steam is acting up. Lobby sharing might not work. Please ensure your Steam Web API Key is correct.** and that's the main reason why I need this to ask to join people and share lobbies ect

**Comment by BeepIsla** [comment]
Did you input a valid API Key ([From here](https://steamcommunity.com/dev/apikey)) in the `steamWebAPIKey` parameter in your `config.json`?

**Comment by JeremyWebb12** [comment]
cant do it im not a paid account
rip

**Comment by BeepIsla** [comment]
There is no other way to get lobby information, nothing I can do.

**Comment by JeremyWebb12** [comment]
thanks for your help ill do this when I have a spare buck :)
